[build-system]
requires = ["setuptools", "pandas"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "314Project1DAG"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
